name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18.x'
    - uses: actions/checkout@v3
    - name: Build all
      run: make

  linter:
    runs-on: ubuntu-20.04
    name: Linter
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.45
        args: --verbose

  project:
    name: Project Checks
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: 1.18.x
    - uses: actions/checkout@v3
      with:
        fetch-depth: 100
    - name: "Check DCO sign"
      run: |
        go install github.com/vbatts/git-validation@v1.1.0
        git-validation -v -run DCO
